// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseAvatar: typeof import('./src/components/BaseAvatar.vue')['default']
    Book: typeof import('./src/components/Bookcase/Book.vue')['default']
    Bookbox: typeof import('./src/components/Bookcase/Bookbox.vue')['default']
    Bookcase: typeof import('./src/components/Bookcase/Bookcase.vue')['default']
    CardHorizontal: typeof import('./src/components/UI/Card/CardHorizontal.vue')['default']
    CardStacked: typeof import('./src/components/UI/Card/CardStacked.vue')['default']
    Cart: typeof import('./src/components/Cart.vue')['default']
    Category: typeof import('./src/components/Header/Category.vue')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    Hero: typeof import('./src/components/HeroSection/Hero.vue')['default']
    HeroBook: typeof import('./src/components/HeroSection/HeroBook.vue')['default']
    Navbar: typeof import('./src/components/Header/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/Header/SearchBar.vue')['default']
    TheFooter: typeof import('./src/components/layouts/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/layouts/TheHeader.vue')['default']
    TheSidebar: typeof import('./src/components/layouts/TheSidebar.vue')['default']
  }
}

export {}
